### ISSUE TITLE
ffuf errors

### ISSUE THREAD

**Issue by alegra8611** [ksharinarayanan/SSRFire#10]
Hi There,

I noticed when probing a target for low hanging fruit with this script I kept on receiving the following error:

Encountered error(s): 2 errors occured.
        * -u flag or -request flag is required
        * Either -w or --input-cmd flag is required

I realised this issue was being generated from ffuf as the script does not pass the required parameters for ffuf to probe,

I changed the following to get it working:

from: 

ffuf FUZZ output/$domain/final_urls.txt $cookie > output/$domain/temp.txt

to:

ffuf -w outuput/$domain/final_urls.txt -u FUZZ

I also deleted the line:

rm output/$domain/temp.txt

This is because I want to see the output,

Just letting you know if you want to append your code :)

Others may have the same issue.

Stay Frosty!

**Comment by alegra8611** [comment]
Further to this,

You can run this tool through burp if you configure you proxychains.conf file to be strict chain through to your burp proxy,

example:

proxychains ssrfire -d https://example.com -s https://ssrftest.com/target

It might be worth to put that in your description

**Comment by ksharinarayanan** [comment]
Hi @alegra8611 , thanks for reporting the issue!
The ffuf error is due to the fact that you haven't run the setup.sh file which adds an ffuf alias to your .profile which has all the required arguements.

Regarding proxychains, I am not too familiar with it! If you can, just send me a pull request, I'll merge it :)
